version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    groups:
      ruby-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    groups:
      docker-minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
